language: python
addons:
  postgresql: 9.3
branches:
  only:
    - master
before_install:
 - git branch -vv | grep '^*'
 - npm install -g marky-markdown
 - sudo apt-get install yajl cffi
 - pip install ijson
cache:
  directories:
    - env/bin
    - env/lib/python2.7/site-packages
install:
 - if [ "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then rm -rf env; fi
 - touch requirements.txt package.json
 - make env
before_script:
 - echo "DATABASE_URL=dbname=gratipay" | tee -a tests/local.env local.env
 - psql -U postgres -c 'CREATE DATABASE "gratipay";'
 - if [ "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then rm -rfv tests/py/fixtures; fi
script: make bgrun test doc
notifications:
  email: false
  irc: false
#sudo: false -- TODO bring back if/when we can work around yajl
